addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.3")
addSbtPlugin("com.github.sbt" % "sbt-findbugs" % "2.0.0")
addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")
addSbtPlugin("com.github.sbt"  % "sbt-native-packager"   % "1.9.7")
addSbtPlugin("io.shiftleft" % "sbt-overflowdb" % "2.26")
