FROM ruby:3.4-alpine

LABEL maintainer="appthreat" \
      org.opencontainers.image.authors="Team AppThreat <cloud@appthreat.com>" \
      org.opencontainers.image.source="https://github.com/appthreat/atom" \
      org.opencontainers.image.url="https://github.com/appthreat/atom" \
      org.opencontainers.image.version="2.2.x" \
      org.opencontainers.image.vendor="appthreat" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.title="atom" \
      org.opencontainers.image.description="Container image for AppThreat atom optimized for Ruby apps" \
      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -it ghcr.io/appthreat/atom-alpine-ruby atom usages --extract-endpoints -o /app/app.atom -l ruby /app"

ENV PATH=/opt/bin:/opt/vendor/bin:${PATH}:/usr/local/bin/:

WORKDIR /opt
COPY ./target/atom.zip .
COPY ./wrapper .
RUN apk update && apk add --no-cache git build-base ruby-dev bash nodejs npm ruby ruby-bundler openjdk21 python3 python3-dev py3-pip \
    && npm install -g corepack \
    && node -v \
    && npm -v \
    && unzip -q atom.zip \
    && cd /opt/nodejs && npm install --omit=dev && cd packages/atom-parsetools && bash build.sh && npm install -g . && cd /opt \
    && python3 -m pip install atom-tools>=0.8.0 --break-system-packages \
    && java --version \
    && npm uninstall -g corepack \
    && apk del npm python3-dev py3-pip build-base git ruby-dev \
    && atom --help \
    && which astgen \
    && which phpastgen \
    && which rbastgen \
    && rbastgen --help \
    && rm -rf /var/cache/apk/*

WORKDIR /app

CMD ["/opt/bin/atom"]
