# frozen_string_literal: true

ruby ">=3.1.4"

source "https://rubygems.org"

group :frontend do
    gem "ruby_ast_gen", github: 'appthreat/ruby_ast_gen', ref: 'v1.0.3'
    gem "parser", "~> 3.3.7.1"
    gem "ostruct", "~> 0.6.1"
    gem "racc", "~> 1.8.1"
end
