# frozen_string_literal: true

ruby ">=3.4.1"

source "https://rubygems.org"

group :frontend do
    gem "ruby_ast_gen", github: 'appthreat/ruby_ast_gen', ref: 'v0.34.2'
    gem "parser", "~> 3.3.7.0"
    gem "ostruct", "~> 0.6.1"
end
