import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  documentation: [
    'intro',
    'installation',
    'container',
    'native',
    'cli',
    'samples',
    'languages',
    'atom-spec',
    'gen-atom',
    'development',
    'using-atom-chennai',
    {
      type: 'category',
      label: 'Atom-Tools',
      link: {
        type: 'doc',
        id: 'atom-tools/atom-tools'
      },
      items: [
        'atom-tools/cli',
        'atom-tools/install',
        {
          type: 'category',
          label: 'Features',
          collapsible: false,
          items: [
            'atom-tools/Features/check',
            'atom-tools/Features/convert',
            'atom-tools/Features/filter',
            'atom-tools/Features/query',
            'atom-tools/Features/validate',
          ],
        }
      ],
    },
    'slicing'
  ],
};

export default sidebars;
