name: Container slices tests

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  lang-container-tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: setup paths
        run: |
          mkdir -p repotests rubyresults scalaresults
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: 'campsite/campsite'
          path: 'repotests/campsite'
          ref: '10197238bbbefd9c9ac7c77467b647fd93993ba0'
          persist-credentials: false
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: 'bionomia/bionomia'
          path: 'repotests/bionomia'
          ref: '5ada8b5f4a5f68561a7195e2badc2f744dc4676e'
          persist-credentials: false
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: 'OWASP/railsgoat'
          path: 'repotests/railsgoat'
          ref: 'c1e8ff1e3b24a1c48fcfc9fbee0f65dc296b49d9'
          persist-credentials: false
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: 'playframework/play-samples'
          path: 'repotests/play-samples'
          ref: '0dccba17856e89dbb5e457ab760efb14cc691395'
          persist-credentials: false
      - name: generate usages - bionomia
        run: |
          mkdir -p $GITHUB_WORKSPACE/rubyresults/bionomia
          cd repotests/bionomia
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom:main atom --help
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom:main rbastgen --help
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-ruby:main rbastgen --help
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-ruby:main atom --help
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-alpine-ruby:main atom --help
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-alpine-ruby:main rbastgen --help
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom:main atom usages --remove-atom -l ruby -o /app/app.atom -s /app/usages.slices.json /app
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-ruby:main atom usages -l ruby -o /app/app.atom -s /app/usages.slices.json /app
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-alpine-ruby:main atom usages -l ruby -o /app/app.atom -s /app/usages.slices.json /app
          ls -lh
          cp *.slices.json $GITHUB_WORKSPACE/rubyresults/bionomia
      - name: generate usages - railsgoat
        run: |
          mkdir -p $GITHUB_WORKSPACE/rubyresults/railsgoat
          cd repotests/railsgoat
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom:main atom usages --remove-atom --extract-endpoints -l ruby -o /app/app.atom -s /app/usages.slices.json /app
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-ruby:main atom usages --extract-endpoints -l ruby -o /app/app.atom -s /app/usages.slices.json /app
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-alpine-ruby:main atom usages --extract-endpoints -l ruby -o /app/app.atom -s /app/usages.slices.json /app
          ls -lh
          cp *.slices.json $GITHUB_WORKSPACE/rubyresults/railsgoat
      - name: generate usages - campsite
        run: |
          mkdir -p $GITHUB_WORKSPACE/rubyresults/campsite
          cd repotests/campsite/api
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom:main atom usages --remove-atom -l ruby -o /app/app.atom -s /app/usages.slices.json /app
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-ruby:main atom usages -l ruby -o /app/app.atom -s /app/usages.slices.json /app
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/appthreat/atom-alpine-ruby:main atom usages -l ruby -o /app/app.atom -s /app/usages.slices.json /app
          ls -lh
          cp *.slices.json $GITHUB_WORKSPACE/rubyresults/campsite
      - name: generate usages - play-samples
        run: |
          mkdir -p $GITHUB_WORKSPACE/scalaresults/play-samples
          cd repotests/play-samples/play-scala-rest-api-example
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -w /app -t ghcr.io/appthreat/atom:main scala --version
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -w /app -t ghcr.io/appthreat/atom:main scalac --version
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -w /app -t ghcr.io/appthreat/atom:main sbt --version
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -w /app -t ghcr.io/appthreat/atom:main scalasem /app /app/semantics.slices.json
          ls -lh
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -w /app -t ghcr.io/appthreat/atom:main atom usages --extract-endpoints -l scala -o /app/app.atom -s /app/usages.slices.json /app
          ls -lh
          cp *.slices.json $GITHUB_WORKSPACE/scalaresults/play-samples
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: rubyresults
          path: rubyresults
        if: matrix.os == 'ubuntu-24.04'
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: scalaresults
          path: scalaresults
        if: matrix.os == 'ubuntu-24.04'
  npm-latest-tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04", "ubuntu-24.04-arm", "macos-15"]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version: '25.x'
          package-manager-cache: false
      - uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d  # v8.1.1
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Install atom latest
        run: |
          npm install -g @appthreat/atom @appthreat/atom-parsetools
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f  # v1.310.0
        with:
          ruby-version: '4.0.0'
          bundler-cache: false
      - name: Check rbastgen 4.0.0
        run: |
          rbastgen --help
