name: nodejstests
on:
  pull_request:
  workflow_dispatch:
jobs:
  nodejs-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java-version: ['19']
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
        with:
          repository: 'ShiftLeftSecurity/shiftleft-java-example'
          path: 'repotests/shiftleft-java-example'
      - uses: actions/checkout@v3
        with:
          repository: 'juice-shop/juice-shop'
          path: 'repotests/juice-shop'
      - uses: actions/checkout@v3
        with:
          repository: 'ShiftLeftSecurity/shiftleft-ts-example'
          path: 'repotests/shiftleft-ts-example'
      - uses: actions/checkout@v3
        with:
          repository: 'libexpat/libexpat'
          path: 'repotests/libexpat'
      - uses: actions/checkout@v3
        with:
          repository: 'HooliCorp/DjanGoat'
          path: 'repotests/DjanGoat'
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - run: |
          # sudo apt install -y rpm rpm-common dpkg dpkg-dev dpkg-sig dpkg-cross lintian fakeroot
          sbt stage astGenDlTask createDistribution
          echo "$GITHUB_WORKSPACE/wrapper/nodejs/plugins/atom-1.0.0/bin/astgen" >> $GITHUB_PATH
          sha512sum target/atom.zip > target/atom.zip.sha512
          cd wrapper/nodejs
          bash build.sh
          sudo npm install -g .
          curl -L https://github.com/joernio/astgen/releases/latest/download/astgen-linux -o /usr/local/bin/astgen
          chmod +x /usr/local/bin/astgen
          atom -l java -o $GITHUB_WORKSPACE/repotests/shiftleft-java-example/cpg_out $GITHUB_WORKSPACE/repotests/shiftleft-java-example
          atom -l js -o $GITHUB_WORKSPACE/repotests/juice-shop/cpg_out $GITHUB_WORKSPACE/repotests/juice-shop
          atom -l js -o $GITHUB_WORKSPACE/repotests/shiftleft-ts-example/cpg_out $GITHUB_WORKSPACE/repotests/shiftleft-ts-example
          atom -l python -o $GITHUB_WORKSPACE/repotests/DjanGoat/cpg_out $GITHUB_WORKSPACE/repotests/DjanGoat
          atom parsedeps -l python -o $GITHUB_WORKSPACE/repotests/DjanGoat/cpg_out $GITHUB_WORKSPACE/repotests/DjanGoat
          atom -l c -o $GITHUB_WORKSPACE/repotests/libexpat/cpg_out $GITHUB_WORKSPACE/repotests/libexpat

  nodejs-testing-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: ['19']
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
        with:
          repository: 'ShiftLeftSecurity/shiftleft-java-example'
          path: 'repotests/shiftleft-java-example'
      - uses: actions/checkout@v3
        with:
          repository: 'juice-shop/juice-shop'
          path: 'repotests/juice-shop'
      - uses: actions/checkout@v3
        with:
          repository: 'ShiftLeftSecurity/shiftleft-ts-example'
          path: 'repotests/shiftleft-ts-example'
      - uses: actions/checkout@v3
        with:
          repository: 'libexpat/libexpat'
          path: 'repotests/libexpat'
      - uses: actions/checkout@v3
        with:
          repository: 'HooliCorp/DjanGoat'
          path: 'repotests/DjanGoat'
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: test
        shell: pwsh
        run: |
          sbt stage astGenDlTask createDistribution
          echo "$env:GITHUB_WORKSPACE\\bin\\astgen" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$env:GITHUB_WORKSPACE\\wrapper\\nodejs\\plugins\\atom-1.0.0\\bin\\astgen" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          cd wrapper\\nodejs
          .\build.ps1
          npm install -g .
          atom -l java -o $env:GITHUB_WORKSPACE\\repotests\\shiftleft-java-example\\cpg_out $env:GITHUB_WORKSPACE\\repotests\\shiftleft-java-example
          atom -l js -o $env:GITHUB_WORKSPACE\\repotests\\juice-shop\\cpg_out $env:GITHUB_WORKSPACE\\repotests\\juice-shop
          atom -l js -o $env:GITHUB_WORKSPACE\\repotests\\shiftleft-ts-example\\cpg_out $env:GITHUB_WORKSPACE\\repotests\\shiftleft-ts-example
          atom -l python -o $env:GITHUB_WORKSPACE\\repotests\\DjanGoat\\cpg_out $env:GITHUB_WORKSPACE\\repotests\\DjanGoat
          atom parsedeps -l python -o $env:GITHUB_WORKSPACE\\repotests\\DjanGoat\\cpg_out $env:GITHUB_WORKSPACE\\repotests\\DjanGoat
          atom -l c -o $env:GITHUB_WORKSPACE\\repotests\\libexpat\\cpg_out $env:GITHUB_WORKSPACE\\repotests\\libexpat
