name: langtests
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lang-testing:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-latest]
        java-version: ['21', '23', '24']
        node-version: ['20.x', '22.x', '23.x']
        ruby: ["3.4.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - uses: actions/checkout@v4
        with:
          repository: 'ShiftLeftSecurity/shiftleft-java-example'
          path: 'repotests/shiftleft-java-example'
      - uses: actions/checkout@v4
        with:
          repository: 'juice-shop/juice-shop'
          path: 'repotests/juice-shop'
      - uses: actions/checkout@v4
        with:
          repository: 'ShiftLeftSecurity/shiftleft-ts-example'
          path: 'repotests/shiftleft-ts-example'
      - uses: actions/checkout@v4
        with:
          repository: 'libexpat/libexpat'
          path: 'repotests/libexpat'
      - uses: actions/checkout@v4
        with:
          repository: 'HooliCorp/DjanGoat'
          path: 'repotests/DjanGoat'
      - uses: actions/checkout@v4
        with:
          repository: 'bionomia/bionomia'
          path: 'repotests/bionomia'
          ref: '5ada8b5f4a5f68561a7195e2badc2f744dc4676e'
      - uses: actions/checkout@v4
        with:
          repository: 'OWASP/railsgoat'
          path: 'repotests/railsgoat'
          ref: 'c1e8ff1e3b24a1c48fcfc9fbee0f65dc296b49d9'
      - uses: actions/checkout@v4
        with:
          repository: 'playframework/play-samples'
          path: 'repotests/play-samples'
          ref: '0dccba17856e89dbb5e457ab760efb14cc691395'
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: sbt/setup-sbt@v1
      - uses: coursier/setup-action@v1
        with:
          apps: scala3 scalac
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"
          tools: composer:v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install sbt
        run: brew install sbt
        if: runner.os == 'macOS'
      - name: Install ubuntu packages
        run: |
          sudo apt update -y
          sudo apt install -y zlib1g php-zip
        if: runner.os == 'Linux'
      - run: |
          sbt stage createDistribution
          python -m pip install atom-tools
          cd wrapper/nodejs
          bash build.sh
          sudo npm install -g .
          atom --help
          astgen --version
          rbastgen --help
          atom -l java -o ${GITHUB_WORKSPACE}/repotests/shiftleft-java-example/app.atom ${GITHUB_WORKSPACE}/repotests/shiftleft-java-example
          atom -l js -o ${GITHUB_WORKSPACE}/repotests/juice-shop/app.atom ${GITHUB_WORKSPACE}/repotests/juice-shop
          atom -l js -o ${GITHUB_WORKSPACE}/repotests/shiftleft-ts-example/app.atom ${GITHUB_WORKSPACE}/repotests/shiftleft-ts-example
          atom -l python -o ${GITHUB_WORKSPACE}/repotests/DjanGoat/app.atom ${GITHUB_WORKSPACE}/repotests/DjanGoat
          atom parsedeps -l python -o ${GITHUB_WORKSPACE}/repotests/DjanGoat/app.atom ${GITHUB_WORKSPACE}/repotests/DjanGoat
          atom -l c -o ${GITHUB_WORKSPACE}/repotests/libexpat/app.atom ${GITHUB_WORKSPACE}/repotests/libexpat
          atom -o ${GITHUB_WORKSPACE}/repotests/railsgoat/app.atom -l ruby ${GITHUB_WORKSPACE}/repotests/railsgoat
          atom -o ${GITHUB_WORKSPACE}/repotests/bionomia/app.atom -l ruby ${GITHUB_WORKSPACE}/repotests/bionomia
          atom -o ${GITHUB_WORKSPACE}/repotests/play-samples/play-scala-rest-api-example/app.atom -l scala ${GITHUB_WORKSPACE}/repotests/play-samples/play-scala-rest-api-example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  nodejs-testing-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java-version: ['21', '22', '24']
        node-version: ['22.x']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
        with:
          repository: 'ShiftLeftSecurity/shiftleft-java-example'
          path: 'repotests/shiftleft-java-example'
      - uses: actions/checkout@v4
        with:
          repository: 'juice-shop/juice-shop'
          path: 'repotests/juice-shop'
      - uses: actions/checkout@v4
        with:
          repository: 'ShiftLeftSecurity/shiftleft-ts-example'
          path: 'repotests/shiftleft-ts-example'
      - uses: actions/checkout@v4
        with:
          repository: 'libexpat/libexpat'
          path: 'repotests/libexpat'
      - uses: actions/checkout@v4
        with:
          repository: 'HooliCorp/DjanGoat'
          path: 'repotests/DjanGoat'
      - uses: actions/checkout@v4
        with:
          repository: 'playframework/play-samples'
          path: 'repotests/play-samples'
          ref: '0dccba17856e89dbb5e457ab760efb14cc691395'
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: sbt/setup-sbt@v1
      - uses: coursier/setup-action@v1
        with:
          apps: scala3 scalac
      - name: build
        shell: pwsh
        run: |
          sbt stage createDistribution
          python -m pip install atom-tools
          cd wrapper\\nodejs
          copy ..\..\target\atom.zip plugins\
          Expand-Archive -Path ..\..\target\atom.zip -DestinationPath plugins\ -Force
          Remove-Item -Force plugins\atom.zip
          php --php-ini php.ini composer.phar require nikic/php-parser:4.18.0 --ignore-platform-reqs --optimize-autoloader
          npm install
          npm install -g .
          get-command atom
          get-command astgen
          get-command phpastgen
          astgen --version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        shell: pwsh
        run: |
          atom -l java --remove-atom -o $env:GITHUB_WORKSPACE\\repotests\\shiftleft-java-example\\app.atom $env:GITHUB_WORKSPACE\\repotests\\shiftleft-java-example
          atom -l python --remove-atom -o $env:GITHUB_WORKSPACE\\repotests\\DjanGoat\\app.atom $env:GITHUB_WORKSPACE\\repotests\\DjanGoat
          atom parsedeps --remove-atom -l python -o $env:GITHUB_WORKSPACE\\repotests\\DjanGoat\\app.atom $env:GITHUB_WORKSPACE\\repotests\\DjanGoat
          atom -l c -o $env:GITHUB_WORKSPACE\\repotests\\libexpat\\app.atom $env:GITHUB_WORKSPACE\\repotests\\libexpat
          atom -l scala -o $env:GITHUB_WORKSPACE\\repotests\\play-samples\\play-scala-rest-api-example\\app.atom $env:GITHUB_WORKSPACE\\repotests\\play-samples\\play-scala-rest-api-example
      - name: test3
        shell: cmd
        run: |
          atom -l js --remove-atom -o %GITHUB_WORKSPACE%\\repotests\\shiftleft-ts-example\\app.atom %GITHUB_WORKSPACE%\\repotests\\shiftleft-ts-example
