name: Release npm package

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  pkg:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      with:
        persist-credentials: false
    - name: Use Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        node-version: '25.x'
        package-manager-cache: false
        scope: '@appthreat'
    - uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d  # v8.1.1
    - name: Set up JDK
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287  # v5.3.0
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821  # v1.4.0
    - uses: coursier/setup-action@fd1707a76b027efdfb66ca79318b4d29b72e5a02  # v3.0.0
      with:
        apps: scala3 scalac
    - name: Build
      run: |
        sudo apt update -y
        sudo apt install -y zlib1g php-zip tree
        sbt stage createDistribution
        sha512sum target/atom.zip > target/atom.zip.sha512
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af  # v1.313.0
      with:
        ruby-version: '4.0.5'
        bundler-cache: false
    - name: Prepare 4.0.0 version
      run: |
        cd wrapper/nodejs
        npm publish --dry-run
    - name: Publish
      run: |
        cd wrapper/nodejs
        bash build.sh
        npm publish --provenance --access=public
      if: startsWith(github.ref, 'refs/tags/')
  npm-release-tests:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    needs: pkg
    permissions:
      contents: read
    steps:
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version: '25.x'
          package-manager-cache: false
      - uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d  # v8.1.1
      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287  # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Install atom latest
        run: |
          npm install -g @appthreat/atom @appthreat/atom-parsetools
          atom --help
      - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af  # v1.313.0
        with:
          ruby-version: '4.0.5'
          bundler-cache: false
      - name: Check rbastgen 4.0.0
        run: |
          rbastgen --help
