name: repotests
on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['11', '17', '19']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: 'ShiftLeftSecurity/shiftleft-java-example'
          path: 'repotests/shiftleft-java-example'
      - uses: actions/checkout@v3
        with:
          repository: 'juice-shop/juice-shop'
          path: 'repotests/juice-shop'
      - uses: actions/checkout@v3
        with:
          repository: 'ShiftLeftSecurity/shiftleft-ts-example'
          path: 'repotests/shiftleft-ts-example'
      - uses: actions/checkout@v3
        with:
          repository: 'libexpat/libexpat'
          path: 'repotests/libexpat'
      - uses: actions/checkout@v3
        with:
          repository: 'HooliCorp/DjanGoat'
          path: 'repotests/DjanGoat'
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - run: |
          sbt stage astGenDlTask
          ./atom -o /tmp/java.cpg.bin -l java $GITHUB_WORKSPACE/repotests/shiftleft-java-example
          ./atom -o /tmp/juice.cpg.bin -l js $GITHUB_WORKSPACE/repotests/juice-shop
          ./atom -o /tmp/ts.cpg.bin -l js $GITHUB_WORKSPACE/repotests/shiftleft-ts-example
          ./atom -o /tmp/py.cpg.bin -l python $GITHUB_WORKSPACE/repotests/DjanGoat
          ./atom -o /tmp/c.cpg.bin -l c $GITHUB_WORKSPACE/repotests/libexpat

          ./atom -o /tmp/java.cpg.bin -l java $GITHUB_WORKSPACE/repotests/shiftleft-java-example --slice --slice-outfile /tmp/java.slices.json
          ./atom -o /tmp/juice.cpg.bin -l js $GITHUB_WORKSPACE/repotests/juice-shop --slice --slice-outfile /tmp/juice.slices.json
          ./atom -o /tmp/ts.cpg.bin -l js $GITHUB_WORKSPACE/repotests/shiftleft-ts-example --slice --slice-outfile /tmp/ts.slices.json
          ./atom -o /tmp/py.cpg.bin -l python $GITHUB_WORKSPACE/repotests/DjanGoat --slice --slice-outfile /tmp/py.slices.json
          ./atom -o /tmp/c.cpg.bin -l c $GITHUB_WORKSPACE/repotests/libexpat --slice --slice-outfile /tmp/c.slices.json

          ./atom -o /tmp/java.cpg.bin -l java $GITHUB_WORKSPACE/repotests/shiftleft-java-example --slice --slice-outfile /tmp/java.usages.json -m Usages
          ./atom -o /tmp/juice.cpg.bin -l js $GITHUB_WORKSPACE/repotests/juice-shop --slice --slice-outfile /tmp/juice.usages.json -m Usages
          ./atom -o /tmp/ts.cpg.bin -l js $GITHUB_WORKSPACE/repotests/shiftleft-ts-example --slice --slice-outfile /tmp/ts.usages.json -m Usages
          ./atom -o /tmp/py.cpg.bin -l python $GITHUB_WORKSPACE/repotests/DjanGoat --slice --slice-outfile /tmp/py.usages.json -m Usages
          ./atom -o /tmp/c.cpg.bin -l c $GITHUB_WORKSPACE/repotests/libexpat --slice --slice-outfile /tmp/c.usages.json -m Usages
          ls -lh /tmp/*.cpg.bin /tmp/*.json
